const symbolsList =
	'BTC,ETH,SOL,SRM,SUSHI,SXP,FTT,YFI,LINK,HGET,CREAM,soUBXT,soHNT,FRONT,AKRO,soHXRO,UNI,soKEEP,soMATH,soALEPH,soTOMO,soLUA,soSWAG,BVOL,IBVOL,AAVE,FIDA,LQID,HOLY,SECO,RSR,CEL,COMP,GRT,PAXG,KIN,USDT,USDC,MAPS,PERP,RAY,OXY,COPE,ROPE,STEP,MEDIA,TULIP,MER,xCOPE,SLIM,SNY,APEX,SLRS,LIQ,SBR,FAB,ORCA,DXL,MNGO,SUNNY,GOFX,CRY,CAVE,ATLAS,POLIS,DFL,MSOL,LIKE,PRISM,WOOF,XTAG,CRWNY,gSAIL,SAMU,GST,BRZ,CYS,CWAR,REAL,MBS,AART,OOGI,CHICKS,RACEFI,SLND,UPS,UNQ,PORT,IN,ABR,RIN,JET,UXP,DATE,SAIL,YARD,SOLC,SOLPAD,BTSL,MOLA,SWARM,DAWG,FANT,LEONIDAS,CHEEMS,SDOGE,WIPE,NAXAR,PRT,SHILL,BOP,ASH,SOLAB,GST,SLX,KURO,CRP,AURY,BNB,LUNA,AVAX,renDOGE,SHIB,MATICpo,AXSet,SAND,MANA,DYDX';

export default symbolsList;
